### ISSUE TITLE
PDO Exception -> Code 42501

### ISSUE THREAD

**Issue by vinny-silveira** [AnatolyUss/FromMySqlToPostgreSql#17]
```php
Message: SQLSTATE[42501]: 
Insufficient privilege: 7 
ERRO:  não pôde abrir arquivo 
"/home/vmoura/Downloads/FromMySqlToPostgreSql-master/temporary_directory/rh_atributo_benefico_colaborador0.csv" 
para leitura: Permissão negada
```

**Comment by AnatolyUss** [comment]
Hello,
You need to grant appropriate "read/write" permissions.
It should be something like:

ALTER DEFAULT PRIVILEGES FOR ROLE [role_name] 
GRANT ALL ON TABLES TO [role_name];

ALTER DEFAULT PRIVILEGES FOR ROLE [role_name] 
GRANT ALL ON SEQUENCES TO [role_name];

Note: you can find more info about PRIVILEGES at: http://www.postgresql.org/docs/9.4/static/sql-alterdefaultprivileges.html

Rerun the script after you solve the "permissioms" issue.

Best regards,
Anatoly
