### ISSUE TITLE
Could not find driver

### ISSUE THREAD

**Issue by b1tdreamer** [AnatolyUss/FromMySqlToPostgreSql#18]
When I launch the script I receive the next error.

 -- FromMySqlToPostgreSql::createSchema
        -- Cannot create a new schema...
        -- PDOException code: 0
        -- File: /home/usuario/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
        -- Line: 292
        -- Message: could not find driver

What do you think it lefts?
Thanks

**Comment by vinny-silveira** [comment]
Looks like you do not have the PDO driver... Install it:
MySQL: ``` sudo apt-get install php5-mysql ``` or for
PostgreSQL: ``` sudo apt-get install php5-pgsql ```

**Comment by anatolyk-investing** [comment]
<b>b1tdreamer</b> - make sure, that you meet all system requirements (listed in README.md).<br />
Use <code>php -v</code> to get SAPI name and version.<br />
Use <code>php -m</code> to see all loaded modules.<br />
Open your php.ini and check <code>register_argc_argv</code>. If disabled - enable it.<br />
Regards...
