### ISSUE TITLE
Missing default clauses

### ISSUE THREAD

**Issue by djfogbr** [AnatolyUss/FromMySqlToPostgreSql#19]
Hi,

I'm trying to use FromMySqlToPostgreSql to migrate a zabbix database. The process mainly goes well, but I'm getting some erros like these:

Message: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "def_shortdata" contains null values
 -- SQL: ALTER TABLE "public"."actions" ALTER COLUMN "def_shortdata" SET NOT NULL;

Then I noticed that the "default" clauses are not exported/imported. For ex, the table "condition" in mysql is defined as:

CREATE TABLE `conditions` (
  `conditionid` bigint(20) unsigned NOT NULL,
  `actionid` bigint(20) unsigned NOT NULL,
  `conditiontype` int(11) NOT NULL DEFAULT '0',
  `operator` int(11) NOT NULL DEFAULT '0',
  `value` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`conditionid`),
  KEY `conditions_1` (`actionid`),
  CONSTRAINT `c_conditions_1` FOREIGN KEY (`actionid`) REFERENCES `actions` (`actionid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8

But when exported to postgres, it is defined as:

CREATE TABLE conditions
(
  conditionid numeric NOT NULL,
  actionid numeric NOT NULL,
  conditiontype integer NOT NULL,
  operator integer NOT NULL,
  value character varying(255),
  CONSTRAINT conditions_pkey PRIMARY KEY (conditionid),
  CONSTRAINT conditions_actionid_fkey FOREIGN KEY (actionid)
      REFERENCES actions (actionid) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE CASCADE
)

Any help?

Thanks in advance.

**Comment by AnatolyUss** [comment]
Hello,
Following log 
<code>Message: SQLSTATE[23502]: Not null violation: 7 ERROR: column "def_shortdata" contains null values
-- SQL: ALTER TABLE "public"."actions" ALTER COLUMN "def_shortdata" SET NOT NULL;</code>
means, that column "def_shortdata" has been declared as <code>NOT NULL</code>, but still contains null values.<br />
Such a situation is very frequant and well known in MySQL world. 
For example:
You could declare "def_shortdata" as <code>NULL</code>.
During one of INSERTs "def_shortdata" accepted value <code>NULL</code> (which is OK for now).
Later, you ALTERed "def_shortdata" to be <code>NOT NULL</code>, and MySQL ACCEPTED such modification.<br />
After such modification "def_shortdata" is <code>NOT NULL</code>, BUT it contains at least one <code>NULL</code> value.
Off course, such case cannot take place when you use PostgreSQL! (SQLSTATE[23502] will be the result)
Regarding <code>DEFAULT</code> clause - currently the <code>processDefault()</code> method is developed in 
not optimal manner... 
For example: 
If an exception was thrown during processing of <code>`conditions`.`conditiontype`</code> - then the 
<code>DEFAULT</code> value will not be set not just for <code>`conditiontype`</code>, but also for rest of 
columns in <code>`conditions`</code> table. 
<br />Sorry, my bad...

**Comment by djfogbr** [comment]
I could also find another different problem. Let's consider another example:

-- Message: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "def_shortdata" contains null values
-- SQL: ALTER TABLE "public"."actions" ALTER COLUMN "def_shortdata" SET NOT NULL;

The definition of the table in mysql is:
CREATE TABLE `actions` (
  `actionid` bigint(20) unsigned NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `eventsource` int(11) NOT NULL DEFAULT '0',
  `evaltype` int(11) NOT NULL DEFAULT '0',
  `status` int(11) NOT NULL DEFAULT '0',
  `esc_period` int(11) NOT NULL DEFAULT '0',
  `def_shortdata` varchar(255) NOT NULL DEFAULT '',
  `def_longdata` text NOT NULL,
  `recovery_msg` int(11) NOT NULL DEFAULT '0',
  `r_shortdata` varchar(255) NOT NULL DEFAULT '',
  `r_longdata` text NOT NULL,
  PRIMARY KEY (`actionid`),
  KEY `actions_1` (`eventsource`,`status`)
) 

The resulting table in postgresql is:
CREATE TABLE actions
(
  actionid numeric NOT NULL,
  name character varying(255) NOT NULL,
  eventsource integer NOT NULL,
  evaltype integer NOT NULL,
  status integer NOT NULL,
  esc_period integer NOT NULL,
  def_shortdata character varying(255),
  def_longdata text,
  recovery_msg integer,
  r_shortdata character varying(255),
  r_longdata text,
  CONSTRAINT actions_pkey PRIMARY KEY (actionid)
)

I think the problem we have here is even more serious: from the "def_shortdata" column on, all the "not null" clauses are also missing in the resulting table.

Thanks in advance.

**Comment by AnatolyUss** [comment]
This is not more serious problem. This is the same problem I've described in my previous comment.
Note,  methods <code>processNull()</code> and <code>processDefault()</code> are completely different methods. If an exception is thrown in one of them, it will never influence another.

**Comment by djfogbr** [comment]
Ok, got it. Btw, Nice work the script, very useful.

Thanks for your attention.
