### ISSUE TITLE
Escape field names

### ISSUE THREAD

**Issue by Michal-sk** [AnatolyUss/FromMySqlToPostgreSql#25]
Since i didnt check out this project and just downloaded it, i dont have a pull request, but here's the patch trough Winmerge:
```
869,870d868
<                 $escapedField = '`' . $arrColumn['Field'] . '`';
< 
873c871
<             		$fieldName = "hex(ST_AsWKB(" . $escapedField . "))";
---
>             		$fieldName = "hex(ST_AsWKB(" . $arrColumn['Field'] . "))";
875c873
<             		$fieldName = $escapedField;
---
>             		$fieldName = $arrColumn['Field'];
```

Basically in ```FromMysqlToPostgreSql.php``` method ```populateTable``` at line ```868``` should escape the field names, since there might be reserved words and than the ```select``` in ```populateTableWorker``` breaks.

**Comment by AnatolyUss** [comment]
Good idea, thanks!
I've just merged it!

**Comment by todenvolkov** [comment]
Thanks, i just had an error with that and got update in a few minutes. Thanks!
