### ISSUE TITLE
privilege errors in log file

### ISSUE THREAD

**Issue by stevetoldme** [AnatolyUss/FromMySqlToPostgreSql#28]
I keep getting these errors but I am not sure why, can you give me a hint? Thanks

	-- FromMySqlToPostgreSql::populateTableWorker

	-- PDOException code: 42501
	-- File: /root/FromMySqlToPostgreSql-master/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 791
	-- Message: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  could not open file "/root/FromMySqlToPostgreSql-master/temporary_directory/action_log0.csv" for reading: Permission denied
	-- SQL: COPY "database_name"."table_name" FROM '/root/FromMySqlToPostgreSql-master/temporary_directory/action_log0.csv' DELIMITER ',' CSV;

	-------------------------------------------------------

**Comment by mobsted** [comment]
I had this error, and solved it when ran script as root

**Comment by AnatolyUss** [comment]
Hi,
Make sure, that username, you use in your PostgreSQL connection string, defined as superuser (usually "postgres").
More info: <a href="http://www.postgresql.org/docs/current/static/app-createuser.html">http://www.postgresql.org/docs/current/static/app-createuser.html</a>

**Comment by stevetoldme** [comment]
Yes, I am running script as root, and using postgres user  in my connection string.

**Comment by AnatolyUss** [comment]
Could you run following query in PostgreSQL, and send me the result:
<code>select * from pg_authid where rolname = 'postgres';</code>
Most necessary is to make sure, that "rolsuper" is true.

**Comment by stevetoldme** [comment]
`postgres=# select * from pg_authid where rolname = 'postgres';
 rolname  | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcatupdate | rolcanlogin | rolreplication | rolconnlimit |             rolpassword             | rolvaliduntil 
----------+----------+------------+---------------+-------------+--------------+-------------+----------------+--------------+-------------------------------------+---------------
 postgres | t        | t          | t             | t           | t            | t           | t              |           -1 | md586db4fdxxxxxxxxxc | 
(1 row)`

**Comment by stevetoldme** [comment]
seems rolsuper is true. Its actually running I just keep getting those errors, and its been running for 24 hours and I am only 10% complete on importing a 20 GB db. Thanks.

**Comment by stevetoldme** [comment]
Just FYI. I let this run for the last 8 days. It actually came close to finishing only had a few more tables but the script terminated with Message: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away ...

Oh well.
