### ISSUE TITLE
Make options in config for field types conversion rules

### ISSUE THREAD

**Issue by mobsted** [AnatolyUss/FromMySqlToPostgreSql#29]
There're many variants of storing date and time in postgresql, while only few in mysql. It would be good, if i could point which of datetime type i want to convert to.
Also, I have columns in MySQL, where i store JSON text - and i would like to have an ability to choose JSON or JSONB filed types for those columns.

**Comment by mobsted** [comment]
And also how to setup rules for NULL or incorrect dates in MYSQL. Sometimes they become NULL cometimes -infinity - what are the rules?

**Comment by AnatolyUss** [comment]
Regarding dates, rules are as follows:
If date was NULL in MySQL, then in PostgreSQL it will be NULL.
If date was '0000-00-00 00:00:00' or '0000-00-00' in MySQL, then in PostgreSQL it will become 
'-infinity '.

Regarding your proposals - in general, they are good, but I'm not sure, that I'll have enough spare-time in the nearest future to implement them.
Consider to fork the project, and implement them yourself.
BTW, thanks for your feedback and for <a href="https://github.com/AnatolyUss/FromMySqlToPostgreSql/issues/26">this issue</a>, it was really valuable!
