### ISSUE TITLE
Can i skip creating constraints on non NULL columns?

### ISSUE THREAD

**Issue by mobsted** [AnatolyUss/FromMySqlToPostgreSql#30]
I have columns in mysql, which are not defined - whether they NULL or NOT NULL - just nothing
. And theese columns after conversion get NOT NULL constraint. Why? How could i skip this rule?
Example:
`Create table Temp(id bigint, name varchar(500)); - name field becomes NOT NULL in postgresql`

**Comment by AnatolyUss** [comment]
When you're not defining NOT NULL explicitly - the column will be NULL by default.
Actually, I have the script working correctly in such case...
I couldn't reproduce this issue.
