### ISSUE TITLE
Success is reported, but there are many PDO errors and no database is created

### ISSUE THREAD

**Issue by agbodike** [AnatolyUss/FromMySqlToPostgreSql#33]
When running the script, it reports success, but I see a number of errors and no database is created. Each time I run it, the database name is incremented.

My relevant JSON config (everything else remains unchanged):

```
"source" : "mysql:host=localhost;port=3306;charset=UTF8;dbname=development_db,root,",
"target" : "pgsql:host=localhost;port=5432;dbname=mysql_import;options=--client_encoding=UTF8,agbodike,",
```

all.log (some select errors):
```
	"FromMySqlToPostgreSql" - the database migration tool
	Copyright 2015  Anatoly Khaytovich <anatolyuss@gmail.com>
	-- Migration began...
-- New schema "development_db_6" was successfully created...
-- 45 tables detected

...

	-- PDOException code: 22P02
	-- File: /Users/agbodike/workspace/agbodike/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 800
	-- Message: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "''"
CONTEXT:  COPY baselines, line 1, column attachment_file_size: "''"
	-- SQL: COPY "development_db_6"."baselines" FROM '/Users/agbodike/workspace/agbodike/FromMySqlToPostgreSql/temporary_directory/baselines0.csv' DELIMITER ',' CSV;

...

	-- PDOException code: 22007
	-- File: /Users/agbodike/workspace/agbodike/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 800
	-- Message: SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type timestamp: "''"
CONTEXT:  COPY credit_cards, line 1, column deleted_at: "''"
	-- SQL: COPY "development_db_6"."credit_cards" FROM '/Users/agbodike/workspace/agbodike/FromMySqlToPostgreSql/temporary_directory/credit_cards0.csv' DELIMITER ',' CSV;

...

	-- FromMySqlToPostgreSql::processForeignKey
	-- Error occurred when tried to create foreign key for table "development_db_6"."baseline_users"...

	-- PDOException code: 23503
	-- File: /Users/agbodike/workspace/agbodike/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 1361
	-- Message: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "baseline_users" violates foreign key constraint "baseline_users_user_id_fkey"
DETAIL:  Key (user_id)=(8) is not present in table "users".
	-- SQL: ALTER TABLE "development_db_6"."baseline_users" ADD FOREIGN KEY ("user_id") REFERENCES "development_db_6"."users" ("id") ON UPDATE RESTRICT ON DELETE RESTRICT;

...

	-- FromMySqlToPostgreSql::populateTableByPrepStmtWorker

	-- PDOException code: 22001
	-- File: /Users/agbodike/workspace/agbodike/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 680
	-- Message: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)
	-- SQL: INSERT INTO "development_db_6"."users" ("id","email","encrypted_password","reset_password_token","reset_password_sent_at","remember_created_at","sign_in_count","current_sign_in_at","last_sign_in_at","current_sign_in_ip","last_sign_in_ip","created_at","updated_at","company_id","is_passcode","first_name","last_name","phone","is_primary","deleted_at","role_id","activated","avatar_file_name","avatar_content_type","avatar_file_size","avatar_updated_at","personal_website","tour_visibility")  VALUES(:0,:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13,:14,:15,:16,:17,:18,:19,:20,:21,:22,:23,:24,:25,:26,:27);
```

That last error looks like it is inserting totally wrong information as I would expect the VALUES to be very different.

**Comment by AnatolyUss** [comment]
Hi,
I've just submitted the path. Please, redownload, and rerun.
Make sure, that:
1. the username, you're using in "target" has the "superuser" privileges.
2. you have to create the target database manually, before running the script.
   For example: <code>CREATE DATABASE "mysql_import";</code>

**Comment by agbodike** [comment]
I updated and re ran, but no change. I already had the database and super user privileges:

```
[local] agbodike@mysql_import=# \l
                                   List of databases
        Name         |   Owner   | Encoding |   Collate   |    Ctype    | Access privileges
---------------------+-----------+----------+-------------+-------------+-------------------
 agbodike            | agbodike  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 mysql_import        | agbodike  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/agbodike         +
                     |           |          |             |             | agbodike=CTc/agbodike
 postgres            | agbodike  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0           | agbodike  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/agbodike          +
                     |           |          |             |             | agbodike=CTc/agbodike
 template1           | agbodike  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/agbodike          +
                     |           |          |             |             | agbodike=CTc/agbodike
(6 rows)

[local] agbodike@mysql_import=# SELECT * FROM pg_catalog.pg_user;
   usename   | usesysid | usecreatedb | usesuper | usecatupd | userepl |  passwd  | valuntil | useconfig
-------------+----------+-------------+----------+-----------+---------+----------+----------+-----------
 agbodike    |       10 | t           | t        | t         | t       | ******** | [NULL]   | [NULL]

[local] agbodike@mysql_import=# \du
                             List of roles
 Role name |                   Attributes                   | Member of
-----------+------------------------------------------------+-----------
 agbodike  | Superuser, Create role, Create DB, Replication | {}
```

**Comment by AnatolyUss** [comment]
Please, explain what does it mean  "it reports success"?
Did you see the last message saying "Migration was successfully accomplished!" and "Total time: ..."?
What exactly was created (empty database, all tables migrated without data, a part of data is missing, etc...)?

Please, send me "all.log" and "errors-only.log" files from the last migration.
Thanks.

**Comment by agbodike** [comment]
yes, migration was successfully accomplished:

```
-- Migration was successfully accomplished!
-- Total time: 00:00:05 (hours:minutes:seconds)
```

I put everything from the logs that looked interesting above, is there anything specific you are looking for?

Do you want me to paste the entire logs here?

**Comment by AnatolyUss** [comment]
You can send me a mail <anatolyuss@gmail.com> with these files attached...
If you don't mind.

**Comment by AnatolyUss** [comment]
Still waiting...

**Comment by agbodike** [comment]
Sorry, I was away on vacation and didn't have my computer. I've emailed you the logs.

**Comment by AnatolyUss** [comment]
Thanks.
Correct me if I'm wrong, but according to logs you've sent, the database was created and all your tables with the data contained in schema "hireq_3".

|  TABLE                                |  RECORDS  |  DATA LOAD TIME  |
	------------------------------------------------------------------------
	|  hireq_3.authentications              |  0        |  0.013 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.baseline_feedback_questions  |  8        |  0.012 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.baseline_users               |  4        |  0.035 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.baselines                    |  1        |  0.034 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.billing_infos                |  1        |  0.033 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.billing_preferences          |  2        |  0.04 seconds    |
	------------------------------------------------------------------------
	|  hireq_3.companies                    |  1        |  0.037 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.credit_cards                 |  0        |  0.036 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.cronbach_alphas              |  0        |  0.015 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.delayed_jobs                 |  0        |  0.018 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.features                     |  0        |  0.014 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.feedback_answers             |  0        |  0.014 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.feedback_questions           |  11       |  0.013 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.feedbacks                    |  0        |  0.036 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.greetings                    |  0        |  0.007 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.group_label_scores           |  0        |  0.009 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.information                  |  0        |  0.009 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.information_users            |  0        |  0.011 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.inquiries                    |  0        |  0.011 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.invites                      |  0        |  0.008 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.jobs                         |  0        |  0.016 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.labelings                    |  0        |  0.014 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.labels                       |  65       |  0.019 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.locations                    |  0        |  0.032 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.notes                        |  0        |  0.024 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.occupation_traits            |  295      |  0.022 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.occupations                  |  100      |  0.037 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.participant_occupations      |  0        |  0.031 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.participant_scores           |  1173     |  0.087 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.participant_statements       |  0        |  0.03 seconds    |
	------------------------------------------------------------------------
	|  hireq_3.participants                 |  1173     |  0.115 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.payment_plans                |  4        |  0.032 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.qualities                    |  7        |  0.032 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.quality_questions            |  14       |  0.041 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.roles                        |  5        |  0.037 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.schema_migrations            |  207      |  0.035 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.scorer_qualities             |  21       |  0.031 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.statements                   |  54       |  0.04 seconds    |
	------------------------------------------------------------------------
	|  hireq_3.survey_responses             |  0        |  0.032 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.surveys                      |  1        |  0.016 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.traitable_traits             |  46       |  0.036 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.traits                       |  23       |  0.038 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.user_subscriptions           |  4        |  0.031 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.users                        |  7        |  0.04 seconds    |
	------------------------------------------------------------------------
	|  hireq_3.vouches                      |  0        |  0.036 seconds   |
	------------------------------------------------------------------------
	|  hireq_3.wishes                       |  0        |  0.028 seconds   |
	------------------------------------------------------------------------

-- Migration was successfully accomplished!
-- Total time: 00:00:05 (hours:minutes:seconds)

**Comment by agbodike** [comment]
That's what it reports, but there is no such database created, or at least
as far as I can tell. Each run results in an increment of the table name,
the next time I run it it would report hireq_4, yet I've not been able to
find a database named as is shown in the output.

Below is my list of tables after the script runs:

[local] afam@afam=# \l
                                   List of databases
        Name         | Owner | Encoding |   Collate   |    Ctype    |
Access privileges
---------------------+-------+----------+-------------+-------------+-------------------
 afam                | afam  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 hireq               | afam  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 mysql_import        | afam  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
=Tc/afam         +
                     |       |          |             |             |
afam=CTc/afam
 postgres            | afam  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0           | afam  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
=c/afam          +
                     |       |          |             |             |
afam=CTc/afam
 template1           | afam  | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
=c/afam          +
                     |       |          |             |             |
afam=CTc/afam
(6 rows)

On Thu, Apr 7, 2016 at 9:58 PM, Anatoly Khaytovich <notifications@github.com
> wrote:

> Thanks.
> Correct me if I'm wrong, but according to logs you've sent, the database
> was created and all your tables with the data contained in schema "hireq_3".
>
> | TABLE | RECORDS | DATA LOAD TIME |
> ------------------------------------------------------------------------
> | hireq_3.authentications | 0 | 0.013 seconds |
> ------------------------------------------------------------------------
> | hireq_3.baseline_feedback_questions | 8 | 0.012 seconds |
> ------------------------------------------------------------------------
> | hireq_3.baseline_users | 4 | 0.035 seconds |
> ------------------------------------------------------------------------
> | hireq_3.baselines | 1 | 0.034 seconds |
> ------------------------------------------------------------------------
> | hireq_3.billing_infos | 1 | 0.033 seconds |
> ------------------------------------------------------------------------
> | hireq_3.billing_preferences | 2 | 0.04 seconds |
> ------------------------------------------------------------------------
> | hireq_3.companies | 1 | 0.037 seconds |
> ------------------------------------------------------------------------
> | hireq_3.credit_cards | 0 | 0.036 seconds |
> ------------------------------------------------------------------------
> | hireq_3.cronbach_alphas | 0 | 0.015 seconds |
> ------------------------------------------------------------------------
> | hireq_3.delayed_jobs | 0 | 0.018 seconds |
> ------------------------------------------------------------------------
> | hireq_3.features | 0 | 0.014 seconds |
> ------------------------------------------------------------------------
> | hireq_3.feedback_answers | 0 | 0.014 seconds |
> ------------------------------------------------------------------------
> | hireq_3.feedback_questions | 11 | 0.013 seconds |
> ------------------------------------------------------------------------
> | hireq_3.feedbacks | 0 | 0.036 seconds |
> ------------------------------------------------------------------------
> | hireq_3.greetings | 0 | 0.007 seconds |
> ------------------------------------------------------------------------
> | hireq_3.group_label_scores | 0 | 0.009 seconds |
> ------------------------------------------------------------------------
> | hireq_3.information | 0 | 0.009 seconds |
> ------------------------------------------------------------------------
> | hireq_3.information_users | 0 | 0.011 seconds |
> ------------------------------------------------------------------------
> | hireq_3.inquiries | 0 | 0.011 seconds |
> ------------------------------------------------------------------------
> | hireq_3.invites | 0 | 0.008 seconds |
> ------------------------------------------------------------------------
> | hireq_3.jobs | 0 | 0.016 seconds |
> ------------------------------------------------------------------------
> | hireq_3.labelings | 0 | 0.014 seconds |
> ------------------------------------------------------------------------
> | hireq_3.labels | 65 | 0.019 seconds |
> ------------------------------------------------------------------------
> | hireq_3.locations | 0 | 0.032 seconds |
> ------------------------------------------------------------------------
> | hireq_3.notes | 0 | 0.024 seconds |
> ------------------------------------------------------------------------
> | hireq_3.occupation_traits | 295 | 0.022 seconds |
> ------------------------------------------------------------------------
> | hireq_3.occupations | 100 | 0.037 seconds |
> ------------------------------------------------------------------------
> | hireq_3.participant_occupations | 0 | 0.031 seconds |
> ------------------------------------------------------------------------
> | hireq_3.participant_scores | 1173 | 0.087 seconds |
> ------------------------------------------------------------------------
> | hireq_3.participant_statements | 0 | 0.03 seconds |
> ------------------------------------------------------------------------
> | hireq_3.participants | 1173 | 0.115 seconds |
> ------------------------------------------------------------------------
> | hireq_3.payment_plans | 4 | 0.032 seconds |
> ------------------------------------------------------------------------
> | hireq_3.qualities | 7 | 0.032 seconds |
> ------------------------------------------------------------------------
> | hireq_3.quality_questions | 14 | 0.041 seconds |
> ------------------------------------------------------------------------
> | hireq_3.roles | 5 | 0.037 seconds |
> ------------------------------------------------------------------------
> | hireq_3.schema_migrations | 207 | 0.035 seconds |
> ------------------------------------------------------------------------
> | hireq_3.scorer_qualities | 21 | 0.031 seconds |
> ------------------------------------------------------------------------
> | hireq_3.statements | 54 | 0.04 seconds |
> ------------------------------------------------------------------------
> | hireq_3.survey_responses | 0 | 0.032 seconds |
> ------------------------------------------------------------------------
> | hireq_3.surveys | 1 | 0.016 seconds |
> ------------------------------------------------------------------------
> | hireq_3.traitable_traits | 46 | 0.036 seconds |
> ------------------------------------------------------------------------
> | hireq_3.traits | 23 | 0.038 seconds |
> ------------------------------------------------------------------------
> | hireq_3.user_subscriptions | 4 | 0.031 seconds |
> ------------------------------------------------------------------------
> | hireq_3.users | 7 | 0.04 seconds |
> ------------------------------------------------------------------------
> | hireq_3.vouches | 0 | 0.036 seconds |
> ------------------------------------------------------------------------
> | hireq_3.wishes | 0 | 0.028 seconds |
> ------------------------------------------------------------------------
>
> -- Migration was successfully accomplished!
> -- Total time: 00:00:05 (hours:minutes:seconds)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AnatolyUss/FromMySqlToPostgreSql/issues/33#issuecomment-207215386>
>



-- 
Afam

**Comment by AnatolyUss** [comment]
Man! 
According to your logs you've created database "mysql_import", and "hireq_3" is just a schema within "mysql_import"!
NOTE:
1. In MySQL a database is an array of tables.
2. In PostgreSQL a database is an array of schemas, and each schema is an array of tables.

You can connect to a database via psql with <code>\c "mysql_import"</code> or <code>\connect "mysql_import"</code>.
When you connected, run for example: <code>SELECT * FROM hireq_3.scorer_qualities</code>

**Comment by agbodike** [comment]
This is news to me about the schema under the schema, but tables can be
directly under the database, which is the behavior I expected. I'm not a
postgres expert by any stretch of the imagination, so I assumed the hireq_3
was a database, not a schema under the database, as I was not aware that is
possible.

Is there a way to have it create the tables under the database, or move the
tables to the desired schema level?

I do know that it's possible to have tables under a top level database
similar to mysql:

[local] afam@mysql_import=# CREATE DATABASE test;
CREATE DATABASE
Time: 347.837 ms

[local] afam@mysql_import=# \c test
You are now connected to database "test" as user "afam".

[local] afam@test=# \dt
No relations found.

[local] afam@test=# CREATE TABLE test_table ( name   varchar(40) NOT NULL
CHECK (name <> '') );
CREATE TABLE
Time: 3.370 ms

[local] afam@test=# \dt
          List of relations
 Schema |    Name    | Type  | Owner
--------+------------+-------+-------
 public | test_table | table | afam
(1 row)




On Thu, Apr 7, 2016 at 11:03 PM, Anatoly Khaytovich <
notifications@github.com> wrote:

> Man!
> According to your logs you've created database "mysql_import", and
> "hireq_3" is just a schema within "mysql_import"!
> NOTE:
> 1. In MySQL a database is an array of tables.
> 2. In PostgreSQL a database is an array of schemas, and each schema is an
> array of tables.
>
> You can connect to a database via psql with \c "mysql_import" or \connect
> "mysql_import".
> When you connected, run for example: SELECT * FROM
> hireq_3.scorer_qualities
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AnatolyUss/FromMySqlToPostgreSql/issues/33#issuecomment-207230907>
>



-- 
Afam

**Comment by AnatolyUss** [comment]
Yes.
In your config.json define <code>"schema": "public"</code>
