### ISSUE TITLE
garbage collection not available

### ISSUE THREAD

**Issue by jamespilcher78** [AnatolyUss/FromMySqlToPostgreSql#36]
Hi,

I'm running Windows 10, Node 5.9.1, MySQL 5.7 and PostGres 9.5

I've successfully migrated a non-trivial database, but to do so I had to comment out './migration/fmtp/FromMySQL2PostgreSQL' line 1021  global.gc();

as it was throwing an error when it got that line "global.gc() is not a function".

Before commenting out the line I tried adding the command line parameter --expose-gc but it seemed to have no effect.

Removing the garbage collection didn't seem to phase my PC (I have 16 GBs of RAM).

Just letting you know in case the issue crops up for other people.

thanks
James

**Comment by AnatolyUss** [comment]
Thanks for the feedback!
