### ISSUE TITLE
Move comments on columns and tables

### ISSUE THREAD

**Issue by fanfouer** [AnatolyUss/FromMySqlToPostgreSql#37]
Hi,

I would find interesting to preserve comments put on columns or tables.
The COMMENT pgsql statement may help to do so.

Btw thank you for this extremely useful stuff ;)

**Comment by AnatolyUss** [comment]
Hi,
Good idea!
I'll implement it during this weekend.

**Comment by AnatolyUss** [comment]
Just updated the 'master'.
Comments creation is implemented.
Thanks for your feedback!
