### ISSUE TITLE
Add option to rename tables, columns, sequences and index in lowercase

### ISSUE THREAD

**Issue by fanfouer** [AnatolyUss/FromMySqlToPostgreSql#38]
Since standard SQL is case insensitive, pgsql force user to add " around mixed-case names as for not seeking them in lower case only.

As a migration tool, this script may expose an option to allow lower-case rewriting of all names took from mysql.
This will prevent user to rewrite all his requests like such :
(mysql)  SELECT * FROM MyTable <=> (pgsql) SELECT * FROM "MyTable" (with appropriate schemas and search_path).

Using SELECT * FROM MyTable in pgsql won't work directly because pgsql will look for mytable instead of MyTable.

**Comment by AnatolyUss** [comment]
Maybe this is a good idea.
I'll consider to include it into the next release.
Thanks for your feedback!
