### ISSUE TITLE
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","

### ISSUE THREAD

**Issue by Sogl** [AnatolyUss/FromMySqlToPostgreSql#4]
Hi!

I'm tried migrate my DB from mysql to postgreSQL and got an error.

Errors-only.log:
```

	-- FromMySqlToPostgreSql::populateTable

	-- PDOException code: 58P01
	-- File: C:\1\FromMySqlToPostgreSql\migration\FromMySqlToPostgreSql\FromMySqlToPostgreSql.php
	-- Line: 624
	-- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "temp/Comment.csv" for reading: No such file or directory
	-------------------------------------------------------


	-- FromMySqlToPostgreSql::populateTable

	-- PDOException code: 58P01
	-- File: C:\1\FromMySqlToPostgreSql\migration\FromMySqlToPostgreSql\FromMySqlToPostgreSql.php
	-- Line: 624
	-- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "temp/Follow.csv" for reading: No such file or directory
	-------------------------------------------------------


	-- FromMySqlToPostgreSql::populateTable

	-- PDOException code: 58P01
	-- File: C:\1\FromMySqlToPostgreSql\migration\FromMySqlToPostgreSql\FromMySqlToPostgreSql.php
	-- Line: 624
	-- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "temp/Installation.csv" for reading: No such file or directory
	-------------------------------------------------------


	-- FromMySqlToPostgreSql::populateTable

	-- PDOException code: 58P01
	-- File: C:\1\FromMySqlToPostgreSql\migration\FromMySqlToPostgreSql\FromMySqlToPostgreSql.php
	-- Line: 624
	-- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "temp/Like.csv" for reading: No such file or directory
	-------------------------------------------------------


	-- FromMySqlToPostgreSql::populateTable

	-- PDOException code: 58P01
	-- File: C:\1\FromMySqlToPostgreSql\migration\FromMySqlToPostgreSql\FromMySqlToPostgreSql.php
	-- Line: 624
	-- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "temp/Post.csv" for reading: No such file or directory
	-------------------------------------------------------


	-- FromMySqlToPostgreSql::createTable
	-- Cannot create table tweather1."User".
	-- PDOException code: 42601
	-- File: C:\1\FromMySqlToPostgreSql\migration\FromMySqlToPostgreSql\FromMySqlToPostgreSql.php
	-- Line: 409
	-- Message: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 1: ...untryCode"  CHARACTER VARYING(3) ,"deviceToken"   ,"displayN...
                                                             ^
	-------------------------------------------------------
```

**Comment by AnatolyUss** [comment]
Hello Artyom,
Look at the following message:

-- FromMySqlToPostgreSql::populateTable

    -- PDOException code: 58P01
    -- File: C:\1\FromMySqlToPostgreSql\migration\FromMySqlToPostgreSql\FromMySqlToPostgreSql.php
    -- Line: 624
    -- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "temp/Comment.csv" for reading: No such file or directory
    -------------------------------------------------------

In "temp/Comment.csv" the "temp" should be a path to temporary directory ("temporary_directory" parameter in the config file).
Usually a path to some directory looks like "/user/path/to/temp" and not "temp"...
Please, edit "temporary_directory" parameter in the config file and rerun the script.

Best regards,
	Anatoly

**Comment by Sogl** [comment]
I use Windows 7 x64.

>Usually a path to some directory looks like "/user/path/to/temp" and not "temp"...

But it creates `temp` folder normally in the script folder. I need slash before?

**Comment by AnatolyUss** [comment]
Value of "temporary_directory" parameter in the config file will be used by PostgreSql server.
Change a value of "temporary_directory" to an absolute path, otherwise PostgreSql server 
will not be able to find it.
I think  C:\1\FromMySqlToPostgreSql  will work.

Could you tell me what data type are you using for column `deviceToken` in table `User`?

**Comment by Sogl** [comment]
>Could you tell me what data type are you using for column deviceToken in table User?

BLOB

**Comment by AnatolyUss** [comment]
Thank you.
Solution will be available very soon (tomorrow in the worst case).

**Comment by Sogl** [comment]
>Solution will be available very soon (tomorrow in the worst case).
Sound good!

Can this script successfully migrate all relations between MySQL tables to PostgreSQL?

Finally I used this script for migration:
https://github.com/mihailShumilov/mysql2postgresql

But it can't do this :disappointed:

**Comment by AnatolyUss** [comment]
Yes.

**Comment by Sogl** [comment]
Ok. I'll try your script after the BLOB fix.

**Comment by Sogl** [comment]
Just tried - all is OK! Nice to see temp folders fix. But I found that not of all my FK is migrated...

Why all tables migrate to new created schema (same name as db name), but not in `public`?

**Comment by AnatolyUss** [comment]
Glad to hear, that this script was helpful!

Creation of a new schema (instead of using "public") 
considered a good practice (at least by me and my colleagues).

It is very unexpected, that not all of your FKs were migrated...
Could you send me (<a href="mailto:anatolyuss@gmail.com">anatolyuss@gmail.com</a>) your db structure (dump without data)?

**Comment by Sogl** [comment]
>Creation of a new schema (instead of using "public") considered a good practice (at least by me and my colleagues).
Unfortunately, many framework postgres connectors can't use nothing except `public` =(

>Could you send me (anatolyuss@gmail.com) your db structure (dump without data)?
Done.

**Comment by AnatolyUss** [comment]
I've just updated config settings.
From now you have a possibility to define the schema name (if still relevant).

**Comment by Sogl** [comment]
>From now you have a possibility to define the schema name (if still relevant).

Good news. I like your quick and good support of this tool :+1:
