### ISSUE TITLE
Duplicated single quotes after migrating

### ISSUE THREAD

**Issue by lucaboesch** [AnatolyUss/FromMySqlToPostgreSql#45]
Thanks for your great script. I discovered double single quotes in PostgreSQL whereas in MySQL there was only a single one. Presumably this happened in line 637 of migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php.
I created pull request #44 which should address this issue.

**Comment by AnatolyUss** [comment]
Thanks for your feedback!
The issue is solved!
