### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by mirabs** [AnatolyUss/FromMySqlToPostgreSql#47]
Hello,

When i run the script, i have this error:

Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "D:\RECETTE\FromMySqlToPostgreSql-master/temporary_directory/t_referentiel0.csv" for reading: No such file or directory

I tried modifying the code by creating the temporary directory with 777 permissions, but i still have the same error.

`mkdir($this->strTemporaryDirectory, 0777, true);	`

What do you think is the problem?

**Comment by AnatolyUss** [comment]
Hi,
I think, that you should run FromMySqlToPostgreSql from the same machine,
where your PostgreSQL installed.

Please, let me know if it helped.

**Comment by mirabs** [comment]
Hi,
Thanks for answering.
Unfortunately, I can't run the script from the same machine where PostgreSQL is installed. . So the problem is from the PostgreSQL copy command which can't access to the file in the other machine. Is there any other solution to this problem?

**Comment by AnatolyUss** [comment]
Unfortunately, this script, in its current state, will not fit you.
Try to find another program.
Sorry...
