### ISSUE TITLE
Move mysql unique indexes to pgsql unique constraints instead of indexes

### ISSUE THREAD

**Issue by gustavecha** [AnatolyUss/FromMySqlToPostgreSql#48]
Hi,

Currently, your script seems to move unique indexes from mysql to pgsql 'unique' indexes.
I think it's better to use constraints with query like : 
ALTER TABLE public."test_table"
  ADD CONSTRAINT test UNIQUE (columns) USING INDEX TABLESPACE pg_default;

instead of things like
CREATE UNIQUE INDEX 
   ON public."iRcom_networks_ipNodes_tags" (name ASC NULLS LAST, value ASC NULLS LAST);

Pgsql's docs say index creation for unique enforcing is a detail of implementation and shouldn't be accessed directly.
https://www.postgresql.org/docs/current/static/indexes-unique.html

I see two big advantages :
- The constraints are visible in information_schema, where unique indexes are not
- Depending on the pgsql views and needs, it may be impossible to deal with foreign keys with unique indexes.

Thank you in advance to deal with this

**Comment by mr-russ** [comment]
This has been resolved in #62.  It needs review and merging before it can be considered complete.

**Comment by AnatolyUss** [comment]
Just merged.  
Thanks for the proposal!
