### ISSUE TITLE
extra data after last expected column

### ISSUE THREAD

**Issue by djfogbr** [AnatolyUss/FromMySqlToPostgreSql#50]
HI,
When trying to import a zabbix database from mysql to postgres using FromMySqlToPostgreSql, I'm finding the following error:

        -- FromMySqlToPostgreSql::populateTableWorker

        -- PDOException code: 22P04
        -- File: /var/lib/pgsql/FromMySqlToPostgreSql-master/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
        -- Line: 641
        -- Message: SQLSTATE[22P04]: Bad copy file format: 7 ERROR:  extra data after last expected column
CONTEXT:  COPY items, line 13500: "40320,8,,,10292,"Jboss activeSessions","grpsum[""{$SERVER_GROUP}"",""jmx[\"jboss.web:type=Manager,pa..."
        -- SQL: SELECT `itemid`,`type`,`snmp_community`,`snmp_oid`,`hostid`,`name`,`key_`,`delay`,`history`,`trends`,`status`,`value_type`,`trapper_hosts`,`units`,`multiplier`,`delta`,`snmpv3_securityname`,`snmpv3_securitylevel`,`snmpv3_authpassphrase`,`snmpv3_privpassphrase`,`formula`,`error`,`lastlogsize`,`logtimefmt`,`templateid`,`valuemapid`,`delay_flex`,`params`,`ipmi_sensor`,`data_type`,`authtype`,`username`,`password`,`publickey`,`privatekey`,`mtime`,`flags`,`interfaceid`,`port`,`description`,`inventory_link`,`lifetime`,`snmpv3_authprotocol`,`snmpv3_privprotocol`,`state`,`snmpv3_contextname`,`evaltype` FROM `items` LIMIT 0, 36445;
COPY "public"."items" FROM '/var/lib/pgsql/FromMySqlToPostgreSql-master/temporary_directory/items0.csv' DELIMITER ',' CSV;

Table definition is as follows:

CREATE TABLE `items` (
  `itemid` bigint(20) unsigned NOT NULL,
  `type` int(11) NOT NULL DEFAULT '0',
  `snmp_community` varchar(64) NOT NULL DEFAULT '',
  `snmp_oid` varchar(255) NOT NULL DEFAULT '',
  `hostid` bigint(20) unsigned NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `key_` varchar(255) NOT NULL DEFAULT '',
  `delay` int(11) NOT NULL DEFAULT '0',
  `history` int(11) NOT NULL DEFAULT '90',
  `trends` int(11) NOT NULL DEFAULT '365',
  `status` int(11) NOT NULL DEFAULT '0',
  `value_type` int(11) NOT NULL DEFAULT '0',
  `trapper_hosts` varchar(255) NOT NULL DEFAULT '',
  `units` varchar(255) NOT NULL DEFAULT '',
  `multiplier` int(11) NOT NULL DEFAULT '0',
  `delta` int(11) NOT NULL DEFAULT '0',
  `snmpv3_securityname` varchar(64) NOT NULL DEFAULT '',
  `snmpv3_securitylevel` int(11) NOT NULL DEFAULT '0',
  `snmpv3_authpassphrase` varchar(64) NOT NULL DEFAULT '',
  `snmpv3_privpassphrase` varchar(64) NOT NULL DEFAULT '',
  `formula` varchar(255) NOT NULL DEFAULT '',
  `error` varchar(2048) NOT NULL DEFAULT '',
  `lastlogsize` bigint(20) unsigned NOT NULL DEFAULT '0',
  `logtimefmt` varchar(64) NOT NULL DEFAULT '',
  `templateid` bigint(20) unsigned DEFAULT NULL,
  `valuemapid` bigint(20) unsigned DEFAULT NULL,
  `delay_flex` varchar(255) NOT NULL DEFAULT '',
  `params` text NOT NULL,
  `ipmi_sensor` varchar(128) NOT NULL DEFAULT '',
  `data_type` int(11) NOT NULL DEFAULT '0',
  `authtype` int(11) NOT NULL DEFAULT '0',
  `username` varchar(64) NOT NULL DEFAULT '',
  `password` varchar(64) NOT NULL DEFAULT '',
  `publickey` varchar(64) NOT NULL DEFAULT '',
  `privatekey` varchar(64) NOT NULL DEFAULT '',
  `mtime` int(11) NOT NULL DEFAULT '0',
  `flags` int(11) NOT NULL DEFAULT '0',
  `interfaceid` bigint(20) unsigned DEFAULT NULL,
  `port` varchar(64) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `inventory_link` int(11) NOT NULL DEFAULT '0',
  `lifetime` varchar(64) NOT NULL DEFAULT '30',
  `snmpv3_authprotocol` int(11) NOT NULL DEFAULT '0',
  `snmpv3_privprotocol` int(11) NOT NULL DEFAULT '0',
  `state` int(11) NOT NULL DEFAULT '0',
  `snmpv3_contextname` varchar(255) NOT NULL DEFAULT '',
  `evaltype` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`itemid`),
  UNIQUE KEY `items_1` (`hostid`,`key_`),
  KEY `items_3` (`status`),
  KEY `items_4` (`templateid`),
  KEY `items_5` (`valuemapid`),
  KEY `items_6` (`interfaceid`),
  CONSTRAINT `c_items_1` FOREIGN KEY (`hostid`) REFERENCES `hosts` (`hostid`) ON DELETE CASCADE,
  CONSTRAINT `c_items_2` FOREIGN KEY (`templateid`) REFERENCES `items` (`itemid`) ON DELETE CASCADE,
  CONSTRAINT `c_items_3` FOREIGN KEY (`valuemapid`) REFERENCES `valuemaps` (`valuemapid`),
  CONSTRAINT `c_items_4` FOREIGN KEY (`interfaceid`) REFERENCES `interface` (`interfaceid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

And the table line where it seems there is a problem follows:

select * FROM items where itemid=40320
--------------

*************************** 1. row ***************************
               itemid: 40320
                 type: 8
       snmp_community: 
             snmp_oid: 
               hostid: 10292
                 name: Jboss activeSessions
                 key_: grpsum["{$SERVER_GROUP}","jmx[\"jboss.web:type=Manager,path=/{$GRAU},host=localhost\",activeSessions]",last,0]
                delay: 30
              history: 90
               trends: 365
               status: 0
           value_type: 3
        trapper_hosts: 
                units: 
           multiplier: 0
                delta: 0
  snmpv3_securityname: 
 snmpv3_securitylevel: 0
snmpv3_authpassphrase: 
snmpv3_privpassphrase: 
              formula: 1
                error: 
          lastlogsize: 0
           logtimefmt: 
           templateid: NULL
           valuemapid: NULL
           delay_flex: 
               params: 
          ipmi_sensor: 
            data_type: 0
             authtype: 0
             username: 
             password: 
            publickey: 
           privatekey: 
                mtime: 0
                flags: 0
          interfaceid: NULL
                 port: 
          description: 
       inventory_link: 0
             lifetime: 30
  snmpv3_authprotocol: 0
  snmpv3_privprotocol: 0
                state: 0
   snmpv3_contextname: 
             evaltype: 0

Any help?
Thanks in advance.

**Comment by AnatolyUss** [comment]
Hi,
I'll check it as soon as possible.

**Comment by mr-russ** [comment]
I would suggest moving to text format as proposed in #56 would resolve this issue.

**Comment by mr-russ** [comment]
Further to #56, #61 also has further improvements to the migration.  Both of those pull requests are likely to resolve your issue.

**Comment by mr-russ** [comment]
The two referenced pull requests resolve this issue and it can be closed unless the reporter can reproduce it again.  Data transfer is a lot more robust with those changes included.

**Comment by djfogbr** [comment]
I'm try to run the import again. Soon I'll post the results here. Thanks a lot.

**Comment by djfogbr** [comment]
No errors with latest version. Thanks a lot!
