### ISSUE TITLE
trouble with cyrrilic

### ISSUE THREAD

**Issue by dekakisalove** [AnatolyUss/FromMySqlToPostgreSql#51]
mysql utf8 to pg utf8, cyrillic are: '???????????? ????????'

**Comment by AnatolyUss** [comment]
Hello,
Probably, this is an encoding issue.
Honestly, I'm not sure, that it is related to migration script.
Please, check encoding settings of your PostgreSQL and pgAdmin (or any other tool you may use). 
Sorry for the late response.
