### ISSUE TITLE
SQLSTATE[42830]: Invalid foreign key: 7 ERROR:  foreign key referenced-columns list must not contain duplicates

### ISSUE THREAD

**Issue by mores** [AnatolyUss/FromMySqlToPostgreSql#53]
Testcase:

create table zero (
        `ID` bigint(20) NOT NULL,
        `DATA` varchar(255) NOT NULL,
        PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

create table one (
        `ID` bigint(20) NOT NULL,
        `DATA` varchar(255) NOT NULL,
        PRIMARY KEY (`ID`),
        CONSTRAINT `one_FK1` FOREIGN KEY (`ID`) REFERENCES `zero` (`ID`)
) ENGINE=InnoDB;

create table two (
        `ID` bigint(20) NOT NULL,
        `one_ID` bigint(20) NOT NULL,   
        `DATA` varchar(255) NOT NULL,
        PRIMARY KEY (`ID`),
        CONSTRAINT `two_FK1` FOREIGN KEY (`one_ID`) REFERENCES `one` (`ID`)
) ENGINE=InnoDB;

create table three (
        `ID` bigint(20) NOT NULL,
        `one_ID` bigint(20) NOT NULL,
        `DATA` varchar(255) NOT NULL,
        PRIMARY KEY (`ID`),
        CONSTRAINT `three_FK1` FOREIGN KEY (`one_ID`) REFERENCES `one` (`ID`)
) ENGINE=InnoDB;

insert into zero values ( 1, 'One' );
insert into one values ( 1, 'One' );
insert into two values ( 1, 1, 'Two' );
insert into three values ( 1, 1, 'Three' );

**Comment by AnatolyUss** [comment]
I'll check it asap.
Thanks!

**Comment by mr-russ** [comment]
When testing on my latest branch with mysql and postgresql 9.6, this works.

**Comment by mr-russ** [comment]
This test example is now in the code and passes a migration.  I feel without further details on how to reproduce it, it should be closed as fixed.
