### ISSUE TITLE
JSON column type

### ISSUE THREAD

**Issue by neokeats** [AnatolyUss/FromMySqlToPostgreSql#54]
Hi, 
I've tried the migration table and it seems not to support the json column type from MySQL.

thanx.
`
-- Currently processing table: bs...
PHP Notice:  Undefined index: json in /root/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/MapDataTypes.php on line 276
PHP Notice:  Undefined variable: sql in /root/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php on line 568
-- Script is terminated.
`

**Comment by AnatolyUss** [comment]
Hi,
I've just pushed the patch.
Please, pull from the master.

**Comment by neokeats** [comment]
thanx for the quick fix, it works !

**Comment by AnatolyUss** [comment]
Glad to help!
