### ISSUE TITLE
FromMySQLToPostgreSQL or NMIG?

### ISSUE THREAD

**Issue by MichaelDBA** [AnatolyUss/FromMySqlToPostgreSql#59]
I was wondering why you are supporting both programs, this one and NMIG?  Is the plan to eventually deprecate this one and continue this good work with NMIG?  If not, can you elaborate on when one would choose this one over NMIG? In other words, when would it be BETTER to use this program instead of NMIG?

Thanks in advance.

**Comment by AnatolyUss** [comment]
It would never be better to use FromMySqlToPostgreSql over nmig.
In my opinion, there are only two types of developers, that will prefer this script over nmig:
1. Those, who don't want or, for some reason, can't install node.js
2. Those, who already has php-cli installed, and thinks, that this script will be good enough
    for their needs. 

In general, this script will produce the same result as nmig, but nmig is very much faster and has
lots of configuration options which are not presented in FromMySqlToPostgreSql.

FromMySqlToPostgreSql is simply a prototype of nmig, but still, a lot of people find it useful...

**Comment by MichaelDBA** [comment]
Great!  Thanks for the elaboration.  NMIG, here I come!

**Comment by AnatolyUss** [comment]
Glad to help!
