### ISSUE TITLE
Script is terminated

### ISSUE THREAD

**Issue by simonjcarr** [AnatolyUss/FromMySqlToPostgreSql#60]
This is the only error message I get and it happens instantly. I have tied the error down the fact that the code is not able to Create the Schema, but I don't know if that is because it is not able to connect or it can not find the server or something else. 

Any ideas?

**Comment by AnatolyUss** [comment]
Make sure your db credentials are correct (in config).
Make sure you have installed PDO...

**Comment by mr-russ** [comment]
Target database might exist with tables that exist.  The screen doesn't print the error as we don't print errors to the screen in the current logging with the way the boolError is set.

**Comment by AnatolyUss** [comment]
It fails when running <code>SELECT schema_name FROM information_schema.schemata </code>.<br>
Hence the reason should be one of following:<br>
1. Wrong pg credentials.<br>
2. PDO is not installed properly.

**Comment by mr-russ** [comment]
#61 also includes information to ensure you have the right modules installed.  See if that helps you identify the cause.
