### ISSUE TITLE
Incorrect number of columns

### ISSUE THREAD

**Issue by weonbin** [AnatolyUss/FromMySqlToPostgreSql#7]
I am trying to convert a database with your script.
it fails with the following error:
```
	-- FromMySqlToPostgreSql::populateTableByPrepStmtWorker
	-- PDOException code: 42601
	-- File: /cygdrive/c/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 575
	-- Message: SQLSTATE[42601]: Syntax error: 7 ERROR:  INSERT has more expressions than target columns
LINE 1: ...sMode" ("id","name","index")  VALUES( $1, $2, $3, '-INFINITY...
                                                             ^
	-- SQL: INSERT INTO "test"."Test" ("id","name","index")  VALUES( :id, :name, :index, '-INFINITY', :index);
```

As you can see, it is trying to insert 5 columns in a table with only 3 columns. It is doing this for all the tables of the database.

Here is the create code for this table:

```
CREATE TABLE `Test` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name` CHAR(10) NOT NULL COLLATE 'utf8_bin',
	`index` BIGINT(20) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `name` (`name`),
	UNIQUE INDEX `index` (`index`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
```

**Comment by AnatolyUss** [comment]
Hello Weonbin,
This issue is solved.
Changes were made only in "migration/FromMySqlToPostgresql/FromMySqlToPostgresql.php" file.
Please, let me know if you have any other issue.

**Comment by weonbin** [comment]
Thank you so much for fixing it so quiickly!

I encounter another issue:
```
-- Currently processing table: ApplicationFramework...
PHP Notice:  Undefined variable: sql in /cygdrive/c/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php on line 471
-- Script is terminated.
```

error log:
```
-- Currently processing table: Test2...

	-- FromMySqlToPostgreSql::createTable
	-- Cannot create table "test"."Test2".
	-- PDOException code: 22023
	-- File: /cygdrive/c/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 463
	-- Message: SQLSTATE[22023]: Invalid parameter value: 7 ERROR:  length for type char must be at least 1 at character 107
```

Create code:
```
CREATE TABLE `Test2` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(60) NOT NULL COLLATE 'utf8_bin',
	`description` CHAR(0) NOT NULL COLLATE 'utf8_bin',
	`index` BIGINT(20) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `name` (`name`),
	UNIQUE INDEX `index` (`index`)
)
COMMENT='TEST'
COLLATE='utf8_bin'
ENGINE=InnoDB
AUTO_INCREMENT=6
;
```

**Comment by AnatolyUss** [comment]
I'll fix it shortly (today).

**Comment by AnatolyUss** [comment]
Fixed.
Changes were made in both 
"migration/FromMySqlToPostgresql/FromMySqlToPostgresql.php" 
and 
"migration/FromMySqlToPostgresql/MapDataTypes.php" files.

Your feedback will be highly appreciated.

**Comment by weonbin** [comment]
Thank you again for the fix!
Your script was able to migrate most of the tables, however it is still running because it is also migrating the views (this database has views returning tens of millions of lines).

Don't you think it would be a good idea to ignore them if it is too difficult to migrate them?

Regarding your fix, I think that you should put a warning in the logs so that the user is aware that the datatype will not be 100% compatible.
In this case, I think that the table had a CHAR(0) in order not to break legacy code that was reading it while preventing having data inserted (you will find every kind of things out there in the DB schema jungle).

Also, a last remark, although all the tables are migrated fine so far, I have an error in the logs for every table:

```
	-- FromMySqlToPostgreSql::populateTable

	-- PDOException code: 58P01
	-- File: /cygdrive/c/FromMySqlToPostgreSql/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 695
	-- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "/cygdrive/c/FromMySqlToPostgreSql/temporary_directory/Test.csv" for reading: No such file or directory
	-- SQL: COPY "test"."Test" FROM '/cygdrive/c/FromMySqlToPostgreSql/temporary_directory/Test.csv' DELIMITER ',' CSV;
```
For information, I am running your script with cygwin.

**Comment by weonbin** [comment]
For information, the conversion has completed without error, it is nice because it would have been a pain to do this by hand ...

Beside views, another improvement could be adding UNIQUE constraints to the target database.

Thank you for saving me days of painful work!

**Comment by AnatolyUss** [comment]
I'm glad to hear my script was helpful!
Proper views creation will be the next improvement.
