### ISSUE TITLE
boolean to bit variyng

### ISSUE THREAD

**Issue by idiengaid** [AnatolyUss/FromMySqlToPostgreSql#71]
Hello very powerfull tool so when i migrate from mysql to postgres object type boolean mysql are migrated in type bit variying so i have some 0 values or postgres is waitng for false value any suggestions.

**Comment by AnatolyUss** [comment]
Hello,
Could you explain what exactly the issue?
MySQL column type Boolean has converted to bit varying?
Actual data hasn't been migrated as you expected?

Please, send me your log files (zipped).
Thanks

**Comment by idiengaid** [comment]
Tks 
So all data are correctly migrated i got no error just in my mysql database  boolean was stored in bit (0,1) now in postgres it use explicitly boolean (true, false). 
For exemple in my mysql database for a column like userenable i have 0 or 1 which is regonized like boolean but in postgres i got 0 or 1 like bit variyng.
I don't know may be  there is somewhere  on yours script i could put something to prevent that?
But once again the script is working perfectly for migrating and creating database
Regards

**Comment by AnatolyUss** [comment]
Try following steps (pg):
1.
If your column bit column has a default value, then run:
alter table "your_table" alter column "your_column" set default null;

If your bit column has no default value, then proceed to step 2.

2.
alter table "your_table" alter column "your_column" type boolean
using("your_column"::text::int::boolean);

Note, queries above should be run on your PostgreSQL db.

Please, let me know if it helped.

**Comment by idiengaid** [comment]
amazing this query work perfectly;
alter table "your_table" alter column "your_column" type boolean using("your_column"::text::int::boolean);
Tks so much
