### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by amaximus** [AnatolyUss/FromMySqlToPostgreSql#74]
Could you please confirm that this tool does not change anything on the source database instance, so tests/experiments can be done from a production source database instance.

Thanks.

**Comment by AnatolyUss** [comment]
Hi,
I confirm that this tool changes nothing in source database.
Feel free to experiment with it.

**Comment by amaximus** [comment]
Thanks.

**Comment by amaximus** [comment]
Works like a charm. Thanks for this great tool.

**Comment by AnatolyUss** [comment]
You're welcome.
Thanks for the feedback!
