### ISSUE TITLE
error on empty table? PDOException code: 58P01

### ISSUE THREAD

**Issue by xtpclark** [AnatolyUss/FromMySqlToPostgreSql#8]
Hello,

I am converting a phpbb3 site - thank you for the excellent tool!  I did have the migration process working well the other day with the same data, etc, but today it is failing after  I pulled master.
commit 837a32ad8f008bf5fd3074eb6d78c8521decd3ed

The CSV file was created, but the actual table in mysql has no rows. Not sure if that can be the issue. I am going to try v1.3.0.

<pre>
        -- PDOException code: 58P01
        -- File: /home/FSPMigrate/my2pg/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
        -- Line: 801
        -- Message: SQLSTATE[58P01]: Undefined file: 7 ERROR:  could not open file "/home/FSPMigrate/my2pg/temporary_directory/phpbb_bbcodes.csv" for reading: No such file or directory
        -- SQL: COPY "public"."phpbb_bbcodes" FROM '/home/FSPMigrate/my2pg/temporary_directory/phpbb_bbcodes.csv' DELIMITER ',' CSV;

        -------------------------------------------------------

</pre>

Thanks!

Perry Clark

**Comment by xtpclark** [comment]
I just switched to 1.3.0 and I am past this problem.
Thank you,

Perry Clark

**Comment by AnatolyUss** [comment]
Hello,
As you probably noticed "MASTER" version is not yet stable, I still work on a few improvements.
Thank you for the feedback!

Best regards,
Anatoly
