### ISSUE TITLE
permission deneied

### ISSUE THREAD

**Issue by paulohbalmeida** [AnatolyUss/FromMySqlToPostgreSql#9]
Hey AnatolyUss, 

Please help!
What user should I run this php?

As you can see , I have a reading permission issue in csv file generated . I have already put the maximum permissions but still can not migrate.

[paulo@localhost temporary_directory]$ tail -f ../logs_directory/all.log 
	-- FromMySqlToPostgreSql::populateTable

	-- PDOException code: 42501
	-- File: /tmp/migrabanco/migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
	-- Line: 807
	-- Message: SQLSTATE[42501]: Insufficient privilege: 7 ERRO:  não pôde abrir arquivo "/tmp/migrabanco/temporary_directory/emp_categoriarelatorio.csv" para leitura: Permissão negada
	-- SQL: COPY "demas_3"."emp_categoriarelatorio" FROM '/tmp/migrabanco/temporary_directory/emp_categoriarelatorio.csv' DELIMITER ',' CSV;
![screen2015-10-27-17-29-18](https://cloud.githubusercontent.com/assets/11232884/10770029/49cad6a4-7cd0-11e5-9660-ac484e29f6af.png)

**Comment by AnatolyUss** [comment]
Hello,
Try to grant appropriate "read/write" permissions.
I think it should be something like:

ALTER DEFAULT PRIVILEGES FOR ROLE [role_name] 
GRANT ALL ON TABLES TO [role_name];

ALTER DEFAULT PRIVILEGES FOR ROLE [role_name] 
GRANT ALL ON SEQUENCES TO [role_name];

Note: you can find more info about PRIVILEGES at: http://www.postgresql.org/docs/9.4/static/sql-alterdefaultprivileges.html  

After you solve the "permissioms" issue, go to  https://github.com/AnatolyUss/FromMySqlToPostgreSql/releases  
and download the latest one (v1.3.0 is stable).

Best regards,
Anatoly
